### ISSUE TITLE
Programmatically expand Accordion

### ISSUE THREAD

**Issue by fuj1w4r4** [GeekyAnts/NativeBase#2380]
Is there anyway to programmatically expand the accordion? 
I tried with set ref then setNativeProps({expanded: 0}) but failed instead.

**Comment by suvenduchhatoi** [comment]
@fuj1w4r4 
Try this way:
```<Accordion
            expanded={2}
            dataArray={dataArray}
/>```

**Comment by SupriyaKalghatgi** [comment]
Closing this issue due to inactivity
Reopen this issue if help needed

**Comment by rawteech** [comment]
Hi, also facing the same problem I would like to expand/ collapse the accordion when a certain event takes place..

**Comment by grahamyesfit** [comment]
I realize I'm a little late to the party, but I solved this issue today. Include a ref property in the Accordion, as follows:
```
<Accordion
  ref={c => (this._accordion = c)}
  dataArray={dataArray}
  renderHeader={this._filterHeader}
  renderContent={this._filterContent}
/>
```
Then, to programmatically expand a tab, you can do this:

`this._accordion.setSelected(n);` (where `n` is the index of the tab you would like to open)

To close all tabs, you can do this:

`this._accordion.setSelected(-1);`

This works with native-base v2.12.1.

**Comment by Dhirajbhujbal** [comment]
@grahamyesfit 

in my case this. _accordion is null

**Comment by sytolk** [comment]
@grahamyesfit accordionRef.setSelected is not a function. Native base 2.13.8
![Screenshot_1579806642](https://user-images.githubusercontent.com/1415463/73015512-d7e3d980-3e24-11ea-907a-ac1a20f3beab.png)

**Comment by sytolk** [comment]
`current` was missing. This works thanks!
`accordionRef.current.setSelected(0);`
