### ISSUE TITLE
DeckSwiper onPress(this.desckSwiper.swipeRight) not working on nativebase 2.1.5 . I have tried every thing discussed earlier regarding deckSwiper.I always get Error(deckSwiper.swipeRight) is not a function.

### ISSUE THREAD

**Issue by sachinsinghh** [GeekyAnts/NativeBase#990]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

**Comment by shivrajkumar** [comment]
#958

**Comment by sachinsinghh** [comment]
@shivrajKumar  Thanx It Worked.
