### ISSUE TITLE
Text component does not render on Android cause of TypeError: this.props.children.toUpperCase is not a function

### ISSUE THREAD

**Issue by andidev** [GeekyAnts/NativeBase#915]
## react-native, react and native-base version
    "native-base": "2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.2",

used to work with 2.1.3 version of native base

does work on ios but not android on 2.1.4

the error message:
![skarmavbild 2017-06-05 kl 11 49 21](https://cloud.githubusercontent.com/assets/571389/26779753/f184aeee-49e6-11e7-9c7f-ae546a7cbbdd.png)

**Comment by shivrajkumar** [comment]
@andidev It would be easier if you could upload the code which is causing this error

**Comment by andidev** [comment]
Sorry for not providing the code. The reason I did not do that was because there where to much code to provide. I was not sure where the errer came from since the emulator did showed the bundled stacktrace.

However today when I upgraded react native again I did not experience this issue anymore. Not sure why since my code have moved a lot. Maybe cause I stopped using native-base TextView in favour of react natives TextView.

So please close this issue if this is a duplicate cause I will not be able to provide any more info on this. Thanks anyway.
