### ISSUE TITLE
Icons not displaying properly when installing via nrpm strategy- seeing [X] instead

### ISSUE THREAD

**Issue by s2t2** [GeekyAnts/NativeBase#76]
I'm using this library and Android Studio to build a react-native android app. Initially, [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) were displaying properly as a result of the `rnpm link` installation strategy. Then I renamed one of the font files (Comic Sans MS), and the icons stopped displaying properly.

I attempted to fix the issue by removing the `android/app/src/main/assets/fonts` and `android/app/build` directories, uninstalling and re-installing this library and peer dependencies. But the icons are still not displaying properly.

I thought the problem only applied to my project's directories, so I created an entirely new react-native application from scratch, created a new Android Virtual Device, re-installed this library and peer dependencies, but the icons are still not displaying properly. I'm confused by this result. 

Please advise. Thank you for your time.

See also: https://github.com/oblador/react-native-vector-icons/issues/233

**Comment by s2t2** [comment]
Here are instructions on how to reproduce the error:

https://gist.github.com/s2t2/d40ee0f20576c18232de828a9e20eab2#file-repro-md

**Comment by s2t2** [comment]
# Reproduction Instructions

## Testing React Native boilerplate

Initialize a new react-native application:

```` sh
react-native init MyNativeApp
cd MyNativeApp/
````

Use Android Studio to start a new Android Virtual Device (AVD) according to the following specs:
  + Android SDK Build Tools 23.0.1
  + Nexus 5 Device
  + Marshmellow 23 x86 OS

Run the react-native packager.

```` sh
react-native run-android
````

The boilerplate application shows up in the AVD as expected.

![figure 1](https://gist.githubusercontent.com/s2t2/d40ee0f20576c18232de828a9e20eab2/raw/100056644daf718c039c5e8df96ad857e867b3d2/FIGURE1.png)

## Testing Native-Base

Shut down the packager and the AVD.

Install native-base.

```` sh
npm install native-base --save
````

Edit `index.android` to use native-base components:

```` js
import React, { Component } from 'react';
import {AppRegistry, Text} from 'react-native';
import {Container, Header, Footer, Title, Content, Button} from 'native-base';

class MyNativeApp extends Component {
  render() {
    return (
      <Container>
        <Header>
          <Title>My Native App!</Title>
        </Header>

        <Content>
          <Text>Hello world.</Text>
        </Content>

        <Footer>
          <Button>Press me!</Button>
        </Footer>
      </Container>
    );
  }
}

AppRegistry.registerComponent('MyNativeApp', () => MyNativeApp);
````

Start the AVD and then the packager to see if native-base components are working:

```` sh
react-native run-android
````

The components are showing up as expected.

![figure 2](https://gist.githubusercontent.com/s2t2/d40ee0f20576c18232de828a9e20eab2/raw/100056644daf718c039c5e8df96ad857e867b3d2/FIGURE2.png)

## Testing Icons

Shut down the packager and the AVD.

Edit `index.android.js`, just the button:

```` js
// ...
<Button>
  <Icon name="ios-radio-outline" />
</Button>
// ...
````

Start the AVD and then the packager to see if the icon is working. As expected, it is not, because the icon assets have not yet been installed. 

![figure 3](https://gist.githubusercontent.com/s2t2/d40ee0f20576c18232de828a9e20eab2/raw/100056644daf718c039c5e8df96ad857e867b3d2/FIGURE3.png)

Shut down the packager and the AVD.

Per the native-base instructions related to Android using `rnpm`, install `react-native-vector-icons`:

```` sh
rnpm link
````

This creates a new directory called `android/app/src/main/assets/fonts` which contains some font files.

Start the AVD and then the packager to see if the icon is working. Unfortunately it is not.

![figure 3](https://gist.githubusercontent.com/s2t2/d40ee0f20576c18232de828a9e20eab2/raw/100056644daf718c039c5e8df96ad857e867b3d2/FIGURE3.png)

**Comment by s2t2** [comment]
OK, so the manual strategy works at least. The weird part about the nrpm strategy is that it was working for me initially. I'm curious to hear if anyone knows why this would no longer be the case.

**Comment by sankhadeeproy007** [comment]
It is very strange indeed. If you're sure that changing the base font family was responsible for it, it might be a problem with native-base. With `rnpm`, it's common for the icons to not work for the first time. However restarting the packager usually fixed the problems. I'll keep it open for a while and see if others have faced the same issue.

**Comment by s2t2** [comment]
Thanks for your attention @sankhadeeproy007 :-)

**Comment by rkmax** [comment]
I'm facing the same error. I tried only the rnpm strategy without success

**Comment by s2t2** [comment]
I think I read that in the very latest version of react native, you can run
`react-native link` as an alternative to using rnpm. I did this for another
library yesterday and it worked fine. I'm curious if this will solve the
issue here. Want to give it a shot?

**Comment by rkmax** [comment]
I've tested with `rnpm link` and `react-native link` without success. the only that is working is the manual entry

```gradle
// android/app/build.gradle
...
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
...
```

**Comment by hugoserrana** [comment]
I think that you have to especify package to link on react native:
Run `react-native link react-native-vector-icons`

This works on react-native 0.32.0

**Comment by GijsGoudzwaard** [comment]
I'm having the exact same issue.
@hugoserrana Tried that, didn't work. I'm also on react-native 0.32.0 and the latest version of native base

**Comment by hugoserrana** [comment]
After run the command, try open Android Studio, clean and rebuild project, check if the project vector-icons will be avaliable after file index finish.

Check the version of gradle plugin too.

**Comment by aloifolia** [comment]
For me, `react-native link react-native-vector-icons` almost worked. When I tried to build the app, I ran into a new error:
````
/[project_path]/node_modules/react-native-vector-icons/android/src/main/java/com/oblador/vectoricons/VectorIconsPackage.java:26: error: method does not override or implement a method from a supertype
  @Override
  ^
1 error
:react-native-vector-icons:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
````

I just deleted the method (it does not seem to exist on 0.47 anymore) and now it works. You should fix this problem.

**Comment by yangqingxian** [comment]
I tried all the suggestions,none of them works.OMG!

**Comment by mtebele** [comment]
1. Close the packager.
2. `react-native link react-native-vector-icons`
3. `cd android/ && ./gradlew clean && cd .. && react-native run-android`
