### ISSUE TITLE
DatePicker type problem (typescript) not assignable to ... after upgrade to 2.7.1

### ISSUE THREAD

**Issue by cgomezmendez** [GeekyAnts/NativeBase#2126]
Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be closed.

After upgrading from native-base 2.7.0 to 2.7.1 I'm getting some errors in my typescript file where DatePicker is, I didn't have the problem just before the upgrade, I attach screenshot of the error.
![problemafterupgrade](https://user-images.githubusercontent.com/2073238/42603539-3d8666a2-853c-11e8-805e-c27c217af689.PNG)

native-base: 2.7.1

**Comment by akhil-geekyants** [comment]
@cgomezmendez `placeHolderText` is still present in `native-base` version 2.7.1.
See line https://github.com/GeekyAnts/NativeBase/blob/v2.7.1/index.d.ts#L822.

**Comment by cgomezmendez** [comment]
After checking the changelog and reading the error I realize the problem is that disabled property is non optional, after I defined it to false the error is gone, but I get another error stating that formatChosenDate does not exist on type... but it works anyways for some reason.
```
Date Picker:
Show default date if placeHolderText prop is not defined. PR #2087, closes #2086
Added disabled prop to prevent user making selection of date. PR #2114, closes #2113
Allow formatting of DatePicker chosen date text. Commit (0b59fb7), closes #2056
```

**Comment by cgomezmendez** [comment]
Seems that the new property formatChosenDate  is missing in the props definition.

**Comment by cgomezmendez** [comment]
I fixed both in pr #2132

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.7.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.7.2)
